version: '3'
services:
  server:
    image: node:18
    command: node packages/back_end/index.js
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./packages:/packages
      - ./node_modules:/node_modules
    restart: always
    ports:
     - "3000:3000"

